### ISSUE TITLE
Compilation error on Mac 10.9, with C++11, clang++

### ISSUE THREAD

**Issue by cloudveil** [neovim/deps#6]
Just noticed an error when moving a personal project over to C++11:

/usr/local/include/msgpack/adaptor/detail/cpp11_msgpack_tuple.hpp(47): error: declaration of a member with the same name as its class

I found that simply commenting that line in cpp11_msgpack_tuple.hpp resolved the issue (?).

**Comment by justinmk** [comment]
we don't use C++
